### ISSUE TITLE
ChangesXpp3Reader chokes on changes.xml if body is not first element

### ISSUE THREAD

**Issue by kirk24788** [1and1/ono-maven-shared#16]
The ChangesXpp3Reader in Version 2.7 chokes on a valid changes.xml if the body element is not the first in the body.

If we create three valid files:
 * `/tmp/changes_prefixed.xml`: (Valid, properties are present before the body element)

        <document xmlns="http://maven.apache.org/changes/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/changes/1.0.0 http://maven.apache.org/plugins/maven-changes-plugin/xsd/changes-1.0.0.xsd">
            <properties>
                <title>Changes</title>
                <author email="user@test.org" />
            </properties>
            <body>
                <release date="1970-01-01" description="Initial Release" version="1.0.0">
                    <action dev="user" type="add">Added stuff</action>
                </release>
            </body>
        </document>
 * `/tmp/changes_suffixed.xml`:  (Valid, properties are present after the body element)

        <document xmlns="http://maven.apache.org/changes/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/changes/1.0.0 http://maven.apache.org/plugins/maven-changes-plugin/xsd/changes-1.0.0.xsd">
            <body>
                <release date="1970-01-01" description="Initial Release" version="1.0.0">
                    <action dev="user" type="add">Added stuff</action>
                </release>
            </body>
            <properties>
                <title>Changes</title>
                <author email="user@test.org" />
            </properties>
        </document>
 * `/tmp/changes_none.xml`:  (Valid, no Properties)

        <document xmlns="http://maven.apache.org/changes/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/changes/1.0.0 http://maven.apache.org/plugins/maven-changes-plugin/xsd/changes-1.0.0.xsd">
            <properties>
                <title>Changes</title>
                <author email="user@test.org" />
            </properties>
        </document>

When running this code, the Changes reader chokes on the document in which the properties are present before the body element:
```
    public static void main(String[] args) throws PolicyException {
        final String[] files = new String[]{"/tmp/changes_suffixed.xml","/tmp/changes_none.xml","/tmp/changes_prefixed.xml"};
        for(final String file : files) {
            System.err.println("*** CHECKING " + file + " ***");
            System.err.println(" -> " + new ChangesReleases(file).getReleases().size() + " releases");
        }
    }
```
results in:
```
*** CHECKING /tmp/changes_suffixed.xml ***
 -> 1 releases
*** CHECKING /tmp/changes_none.xml ***
 -> 1 releases
*** CHECKING /tmp/changes_prefixed.xml ***
Exception in thread "main" org.apache.maven.shared.release.policy.PolicyException: Could not read changes from /tmp/changes_prefixed.xml
	at net.oneandone.maven.shared.ChangesReleases.getReleases(ChangesReleases.java:52)
	at com.unitedinternet.mamido.assetmanagement.qa.request.resolvers.ChangesResolver.main(ChangesResolver.java:97)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unrecognised tag: 'body' (position: START_TAG seen ...</properties>\n            <body>... @8:19) 
	at net.oneandone.maven.shared.changes.model.io.xpp3.ChangesXpp3Reader.parseProperties(ChangesXpp3Reader.java:816)
	at net.oneandone.maven.shared.changes.model.io.xpp3.ChangesXpp3Reader.parseChangesDocument(ChangesXpp3Reader.java:637)
	at net.oneandone.maven.shared.changes.model.io.xpp3.ChangesXpp3Reader.read(ChangesXpp3Reader.java:1167)
	at net.oneandone.maven.shared.changes.model.io.xpp3.ChangesXpp3Reader.read(ChangesXpp3Reader.java:1198)
	at net.oneandone.maven.shared.ChangesReleases.getReleases(ChangesReleases.java:47)
	... 1 more
```

**Comment by mfriedenhagen** [comment]
After some inspection:
* The problem is the empty `author` tag.
* Accessors are created via the modello-maven-plugin, I do not want to fiddle with this (or create an issue there).
* `maven-changes-plugin` fails to create a report correctly as well.
